server:
  port: 8081

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**   # your endpoints
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
