server:
  port: 8081

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/oauth2/**, /.well-known/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
